# Site settings
title: Sònar STUDIO
email: sonarstudio@domain.com
url: https://example.github.io
#description will appear in your document head meta (for Google search results) and in your feed.xml site description."
description: "La solution tout en un pour votre album et vos envies de musique."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Sòoar Studio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/sonarstudio
  - title: facebook
    url: https://facebook.com/sonarstudio
  - title: github
    url: https://github.com/sonarstudio

exclude: 
  - README.md
  - LICENCE

# Build settings
markdown: kramdown
permalink: pretty
